### ISSUE TITLE
Can't seem to combine autofocus and invoke

### ISSUE THREAD

**Issue by jorisw** [bfanger/angular-keyboard#11]
Hi,

I'm trying to get a `kb-select` autofocused, so that the user can immediately use the arrow keys on it (without tabbing into it), then hit Space or Enter to invoke an event.

I tried a select box with `kb-autofocus`, which does auto focus the list and enable arrow keys:
```
<div class="list card networks" ng-if="networks">
  <div class="item item-divider">Please choose a network</div>
  <select multiple class="item item-body" kb-select ng-model="networks[0]" kb-autofocus="networks.length > 0" autofocus>
    <option ng-repeat="network in networks" value="{{network.SSID}}" kb-item="network" kb-invoke="selectNetwork(network)" >
      {{network.SSID}}
    </option>
  </select>
  <ion-spinner icon="crescent"></ion-spinner> Scanning for networks...
  ...
```
However, neither `space` nor `enter` trigger the `kb-invoke`.

I tried a `ul` list with `kb-autofocus`, which doesn't auto focus, requiring the user to tab into it:
```
<div class="list card networks" ng-if="networks">
  <div class="item item-divider">Please choose a network</div>
  <ul multiple class="item item-body" kb-select ng-model="networks[0]" kb-autofocus="networks.length > 0" autofocus>
    <li ng-repeat="network in networks" kb-item="network" kb-invoke="selectNetwork(network)" >
      {{network.SSID}}
    </li>
  </ul>
  <ion-spinner icon="crescent"></ion-spinner> Scanning for networks...
  ...
```
However, `space` and `enter` do trigger the `kb-invoke`.

How do I achieve the best of both worlds?

**Comment by jorisw** [comment]
Fixed my own problem as follows:

- Set attribute `kb-select` to the `ul` list.
- Put a `kb-focus="list-item-{{($index+1)}}"` on the first `li` in my list
- From the controller, call `kbFocus('list-item-1')`.
- Set a `kb-invoke` on each list item.

My list is now immediately navigable using the up / down arrows.

**Comment by realph** [comment]
@jorisw How did you put a `kb-focus="list-item-{{($index+1)}}"` on the first item in an `ng-repeat`?

**Comment by jorisw** [comment]
Just by putting that attribute in there, literally. Yes, it would do the same for all the `li`s but it's the kbFocus call that's aimed at `list-item-1`.
