### ISSUE TITLE
Option to select an entry through code.

### ISSUE THREAD

**Issue by bjdash** [bfanger/angular-keyboard#12]
Is there any way I can select an entry through JavaScript?

**Comment by bfanger** [comment]
Yes, just update the model of the ng-list

**Comment by bjdash** [comment]
You mean to update the value of  ng-model of the tag that has the directive kb-list??

I was looking for more of a api function by calling which I can select the item. By exposing an api will allow me to select next or previous item through code.

**Comment by bfanger** [comment]
Yes, that is what i meant.

angular-keyboard doesn't have notion of "next" or "previous" only "up", "down", "left" and "right" but doesn't expose those an api/service.

**Comment by bjdash** [comment]
I would suggest to expose an api because its verumuch usefull. Also you have followed a very well structured code so I think it will be easier to expose the api.
