### ISSUE TITLE
Document the model

### ISSUE THREAD

**Issue by jorisw** [bfanger/angular-keyboard#13]
Please document what the `ng-model` in the examples stands for, and how it could be utilized to manipulate the state of the list.

**Comment by 0xorial** [comment]
+1

**Comment by smff** [comment]
+1

**Comment by portus84** [comment]
+1

**Comment by bfanger** [comment]
The `ng-model`stands for the **selected item(s)**
It only affect the selection, the other states of the list are managed by other directives like `ng-repeat` and `ng-if`
