### ISSUE TITLE
Can't initialize kb-list with model object

### ISSUE THREAD

**Issue by jorism5** [bfanger/angular-keyboard#14]
Hi,
I use `kb-list` with an object list.
```html
<div kb-list ng-model="vm.selected">
  <div ng-repeat="item in items" kb-item="item">{{item.id}}</div>
</div>
```
where items are:
`[{id:1}, {id:2}, {id:3}]`
That works fine.
But when I tried to initialize the list with`$scope.vm.selected = {id:1}` in my controller,  nothing happens.
Do I make something wrong?
Thanks

**Comment by bfanger** [comment]
It must be the same instance of the object, try:
```
$scope.vm.selected = $scope.items[0];
```

**Comment by jorism5** [comment]
That works fine, thanks!
