### ISSUE TITLE
kbItem Triggers a scope.apply on click

### ISSUE THREAD

**Issue by masterkidan** [bfanger/angular-keyboard#22]
![image](https://cloud.githubusercontent.com/assets/942002/21950674/3ec1b7d8-d9b2-11e6-84b7-8b251f49d2b9.png)

Hello, 
Am interested in knowing why kbItem requires to do a scope.apply on el.'click'. Would expect angular-keyboard to only worry about key strokes. 

Additionally, could you use evalAsync instead of doing a .$apply, as it is a bit more efficient?

Thanks

**Comment by bfanger** [comment]
Clicking on an kb-item sets the ng-model of the kb-list or kb-select, but the el.click is a DOM event listener, which is called outside a angular digest, so to let the rest of the application know a about the change and let angular update the view a $rootScope.$digest() must take place.


$evalAsync isn't "a bit more efficient" but is actually slower.

**$apply**
Calling $scope.$apply() applies the expresion if one is given (not in the kb-item click case) and starts the digest.

**$evalAsync**
$evalAsync checks if a digest is in progress and if not it [schedules a digest](https://github.com/angular/angular.js/blob/07849779ba365f371a8caa3b58e23f677cfdc5ad/src/ng/rootScope.js#L1008) with $browser.defer (a setTimeout)

**Comment by masterkidan** [comment]
By efficient I didnt mean faster, was just trying to avoid triggering a digest on the entire app for updating one particular model on a specific directive. 
Could you perhaps consider this instead (if updating the model immediately was the concern): 
https://www.bennadel.com/blog/2595-using-scope-digest-as-a-performance-optimization-in-angularjs.htm ? 

The trouble is in a large app, which has around a 1000 odd watchers doing a $scope.$apply ends up triggering long digest cycles, scoping it down may help some of the perf implications (which is what the screenshot is indicating).

**Comment by bfanger** [comment]
Ah, i see. The click changes the selected item, this is not part of the directive, so I need to trigger $scope.apply() to let the application handle the change.

**Comment by masterkidan** [comment]
If the directive doesn't care about the selected item, why does it actually trigger a $scope.apply? I don't quite understand the need for it. 
The parent directive/component is bound separately to the item in any case, and should handle the click event on its own. 

Could you make the triggering of apply be based on a parameter? Default is on, if param specified then don't trigger it? 
I can create a PR for this.

**Comment by bfanger** [comment]
For example you make a tabs directive and to make it keyboard-aware you'd sprinkle some angular-keyboard directives in there.
If I don't run the $scope.apply the view will not be updated and still show the old tab selected.

> Could you make the triggering of apply be based on a parameter? 

No, if you don't if you don't want it to do something, don't place the kb-item detective.

**Comment by masterkidan** [comment]
If there is a tabs directive I would end up using kb-item like so: 
<tabs>
   <tab ng-click="onTabClick" kb-item/>
</tabs>

Now the ng-click on the tab will take care of doing a scope.apply, There is no need for kb-item to end up doing the scope.apply, unless the "Enter key" or the equivalent selector key is pressed.

Is the above not the intended use case for kb-item?

**Comment by bfanger** [comment]
kb-item handles both mouse and keyboard input, so no need for a ng-click.
You could add a keyboard-only option to kb-select and kb-list. But what in which scenario do want a item to be only selectable with a keyboard and not by click? On a website?

**Comment by bfanger** [comment]
I'll have to check if ngModel.$setViewModel() is also triggering a $scope.apply() because that would mean that digest is run twice.

**Comment by masterkidan** [comment]
I see, I guess there was a misunderstanding of the use case then. In our app, we are currently using kb-item as a means for doing keyboard navigation, and handling click/mouse-over events separately as part of the parent directive. Feel free to close the issue.
