### ISSUE TITLE
Space not working in text input field anymore if kb-item is defined on input directive

### ISSUE THREAD

**Issue by irinelpascu** [bfanger/angular-keyboard#24]
Hi guys,

Great job for angular-keyboard!

I have a list selector with an input text for filtering.
I added angular-keyboard to navigate up and down through the list and it works.
The problem is that kb-item prevents default even for text inputs so i cannot write the space character in the input because of the event.preventDefault() in keyboard.js:460
The prevent default shouldn't happen on text inputs.

Thank you,
Irinel

**Comment by irinelpascu** [comment]
I found a way to hack it although it is not nice
I added to the input directive: `kb-invoke="$ctrl.addSpaceToText()`
And in the controller: `addSpaceToText() {
    this.searchText += ' ';
  }`

**Comment by bfanger** [comment]
kb-item was not build with `<input>` in mind.
To focus inputs the normal tab was sufficient in my use-case.

Envisioning a list with multiple inputs is like an excel sheet, but even excel doesn’t navigate between inputs, you focus a field and then press a key to enter edit-mode.
