### ISSUE TITLE
Two focused items in a list. One by mouse hover one by navigation for arrows

### ISSUE THREAD

**Issue by irinelpascu** [bfanger/angular-keyboard#25]
I am using angular-keyboard to navigate through a list with up and down arrows.
I also want to support hovering with the mouse over the items.
The problem is that we can have two hovered (focused) items (one by mouse hover one by navigation for arrows) which is not nice
Is there a way we can prevent having two items focused?

**Comment by bfanger** [comment]
I think you can override the style for the focused one with the sibling selector:

```css
.item:hover ~ .item {
  background: white !important;
}
```
Or focus the item on mouse enter, but both of these solutions have issues. As there is a difference between focus and hover. I recommend to style these states differently. Making the focus state slightly darker for instance.

**Comment by irinelpascu** [comment]
I found a workaround for this as well. I am forcing the style from the parent of the items
`
parent {
        &:hover > item {
          &:focus {
            background-color: unset;
          }
          &:hover {
            background-color: $color_hover;
          }
        }
      }
`
On the child I am only handling the case where the mouse is not hovering the container so just focus needs to be treated
`
item {
  &:focus {
    background-color: $color_hover;
    outline: none;
  }
}
`
Thank you for your help
