### ISSUE TITLE
KB-focus not working on first element of md-list if first element is deleted

### ISSUE THREAD

**Issue by Agulbaw** [bfanger/angular-keyboard#26]
I am using kb-focus for focus on md list 

<md-list-item
                    ng-repeat="observation in vm.observationOb track by observation.observationId"
                    ng-click="vm.eventHandler($event)"
                    md-ink-ripple="false"
                   ng-class="$index % 2 == 0 && 'evenrow' || 'oddrow'"
                    kb-item="observation"
                    kb-focus="observation-{{observation.observationId}}"
                    >

In the controller, I am calling kbfocus(observation.observationId) after the list is refreshed.

where observationId is the first element of the list.

When I delete first element of the list, the focus doesn't come on the first item of the list. The focus does come on the first item when a non first element is deleted. I have checked that the observationId is of the first element of the newly returned list.

Any suggestions?

**Comment by bfanger** [comment]
I'm no longer actively maintaining this package (i no longer use angular).
So i'll won't be fixing bugs or building new features. 

But i'll generally will merge PR's, so feel free to create a fix.
