### ISSUE TITLE
Errors in console if we hide the list on click/enter

### ISSUE THREAD

**Issue by manindr** [bfanger/angular-keyboard#27]
If you hide the list just after clicking on an item, then it throws following error in console. 

angular.js:13561 TypeError: Cannot read property 'nodeName' of null
    at Object.getScrollParent (kbScroll.js:48)
    at Object.focus (kbScroll.js:135)
    at KbContainerController.activate (kbList.js:20)
    at HTMLButtonElement.<anonymous> (kbItem.js:156)
    at HTMLButtonElement.dispatch (jquery.js:5183)
    at HTMLButtonElement.elemData.handle (jquery.js:4991)
    at HTMLButtonElement.keydownHandler (clickDecorators.ts:293)
    at HTMLButtonElement.dispatch (jquery.js:5183)
    at HTMLButtonElement.elemData.handle (jquery.js:4991)

This is happening because it can't find a parent anymore because it's not there in DOM.

       this.getScrollParent = function (el) {
          var parent = el.parentElement;
         while (parent.nodeName !== viewportNode) {
            var parentStyle = getComputedStyle(parent);
            var overflowStyle = parentStyle.overflow + parentStyle.overflowX + parentStyle.overflowY;
            if (overflowStyle.match(/scroll|hidden/)) {
                break;
            }
            parent = parent.parentElement;
        }
        return parent;
    };

change while loop arguments to 

     this.getScrollParent = function (el) {    
        var parent = el.parentElement;
         while (parent && parent.nodeName !== viewportNode) {
            var parentStyle = getComputedStyle(parent);
            var overflowStyle = parentStyle.overflow + parentStyle.overflowX + parentStyle.overflowY;
            if (overflowStyle.match(/scroll|hidden/)) {
                break;
            }
            parent = parent.parentElement;
        }
        return parent;
    };

and put further null checks on returned value.

**Comment by bfanger** [comment]
I'm no longer actively maintaining this package (i no longer use angular).
So i'll won't be fixing bugs or building new features. 

But i'll generally will merge PR's, so feel free to create a fix.
