### ISSUE TITLE
Too many watchers

### ISSUE THREAD

**Issue by yoyoprs** [bfanger/angular-keyboard#9]
For 500 entries in ng-repeat, i got around 2000 wachers !

**Comment by bfanger** [comment]
Could you provide the offending code of the ng-repeat? And preferably a suggestion on how to optimize. Is 4 watchers per row that bad?

**Comment by yoyoprs** [comment]
it is not recommended to have more than 2,000 watchers with angularjs, it is a question of performance

**Comment by bfanger** [comment]
kb-item uses $watch to respond to changes, they are there for a reason.

I could rewrite it to use only 1 watcher, but it would have to do the same things so it wouldn't have any performance benifit.

If a specific watcher count is important to you, reduce the list from 500 to X entries until you've reaches your defined maximum.
